#!/bin/bash

echo "YandereSatsukiFreedomKernel Buildscript"
echo

exitfn () {
    trap SIGINT              # Restore signal handling for SIGINT
    echo " "
    echo "Aborted."
    sed -i 's/-'"$kernel_version"'/placeholder/g' arch/arm64/configs/kitakami_satsuki_defconfig
    exit                     #   then exit script.
}

function goto
{
    label=$1
    cmd=$(sed -n "/$label:/{:a;n;p;ba};" $0 | grep -v ':$')
    eval "$cmd"
    exit
}

MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$MY_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

# Tuneables Here
toolchain="aarch64-linux-gnu-7.1.1"
prefix="aarch64-linux-gnu-"
toolchain_path="/home/pdesire/kernel/toolchains/$toolchain/bin/:$PATH"
name_of_your_kernel="XperiaSatsukiEliteKernel"
kernel_version="Upstream-Tristan-Marsell"
cpu_jobs="`grep -c ^processor /proc/cpuinfo`"
kerneltype="Image.gz-dtb"
cmdline="androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 boot_cpus=0-5 dwc3_msm.hvdcp_max_current=1500 dwc3_msm.prop_chg_detect=Y coherent_pool=2M androidboot.selinux=permissive zram.backend=z3fold buildvariant=userdebug"
author="Tristan Marsell <tristan.marsell@t-online.de>"
DATE="`date '+%Y-%m-%d'`"
ps=4096
base=0x00000000
ramdisk_offset=0x02000000
tags_offset=0x01E00000

export CLANG_HOST=yes

export ARCH=arm64
export PATH=$toolchain_path
export CROSS_COMPILE=$prefix

trap "exitfn" INT            # Set up SIGINT trap to call function.

# Go to kernel root
cd $MY_PATH

sed -i 's/placeholder/-'"$kernel_version"'/g' arch/arm64/configs/kitakami_satsuki_defconfig

while read -p "Do you want to make clean (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		echo "Removing old files..."
		rm -rf final_files
		rm -rf logs
		make mrproper -j$cpu_jobs 
		rm -rf arch/arm64/boot/"$kerneltype"
		
		echo "Create new folders..."
		mkdir final_files
		mkdir logs
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo "For which device you want to create kernel?"

PS3='Please enter your choice: '
options=("satsuki" "Quit")
select opt in "${options[@]}"
do
	case $opt in
        "satsuki")
            defconfig="kitakami_satsuki_defconfig"
            target="Xperia Z5 Premium"
            device_name="E6853"
            device_codename="satsuki"
            goto secondstep
            ;;
        "Quit")
            goto end
            ;;
        *) echo invalid option;;
    esac
done

secondstep:


# Make Defconfig
make $defconfig -j$cpu_jobs |& tee logs/log_defconfig.txt
echo
echo "Done"

echo " "
echo " "
echo "##################################################"
echo "Kernel Infos:"
echo "Bootsplash Kernel Name: $name_of_your_kernel"
echo "SoC (ARCH) Type: AARCH64 (ARM64)"
echo "Used Defconfig: $defconfig"
echo "Used Diffconfig: $diffconfig"
echo "Kerneltype: $kerneltype"
echo "--------------------------------------------------"
echo "Ramdisk Infos:"
echo "Ramdisk Cmdline: $cmdline"
echo "Pagesize: $ps Kilobytes"
echo "Base: $base"
echo "Ramdisk Offset: $ramdisk_offset"
echo "Tags Offset: $tags_offset"
echo "--------------------------------------------------"
echo "Build Infos:"
echo "Build Target Device: $target"
echo "Toolchain: $toolchain"
echo "Threads: $cpu_jobs"
echo "Buildscript Author: $author"
echo "Build Date: $DATE"
echo "##################################################"
echo " "
echo " "
echo " "

# Build Kernel
sleep 2s
echo "Start building kernel..."
make -j$cpu_jobs |& tee logs/log_build.txt
echo "Done"
echo



if [ -f arch/arm64/boot/"$kerneltype" -a ! -f final_files/*.img ]; then
	echo "Making boot.img..."
	./scripts/mkbootimg --cmdline "$cmdline" --base $base --kernel arch/arm64/boot/Image.gz-dtb --ramdisk elitekernelfiles/$device_codename/ramdisk.cpio.gz --ramdisk_offset $ramdisk_offset --pagesize $ps -o final_files/boot_$device_name.img --tags_offset $tags_offset

else 
	echo "$kerneltype not found, take a look on logs folder to see what causes the problem. Aborted."
fi

if [ -f final_files/*.img ]; then
	# Packing to ZIP
	cp -f elitekernelfiles/$device_codename/init.qcom.post_boot.sh flashscripts/system/etc
	cp -fr flashscripts/* final_files
	cd final_files
	mv boot_$device_name.img boot.img
	zip -r $device_codename.$name_of_your_kernel.zip *
	cd ..
	mkdir uploads
	mv final_files/$device_codename.$name_of_your_kernel.zip uploads/$device_codename.$DATE.$name_of_your_kernel.$kernel_version.zip
	rm -f flashscripts/system/etc/init.qcom.post_boot.sh

else
	echo "boot.img not found. Aborted."
fi

sed -i 's/-'"$kernel_version"'/placeholder/g' arch/arm64/configs/kitakami_satsuki_defconfig

end:
trap SIGINT                  # Restore signal handling to previous before exit.
exit 0;
